[common]
include_remarks=美国|US|JP|日本|HK|香港|SG|新加坡|TW|台湾|韩国|KR
[custom]
;规则集合

; 广告拦截
ruleset=拦截,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Advertising/Advertising_All.list
; 梯子检查
ruleset=检查,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Proxy/Proxy.list
ruleset=检查,https://raw.githubusercontent.com/olddoge/ACL4SSR-Aznable/refs/heads/master/Ruleset/ProxyCheck.list
ruleset=检查,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Speedtest/Speedtest.list
; 直连
ruleset=大陆,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/China/China.list
ruleset=大陆,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/ChinaDNS/ChinaDNS.list
ruleset=大陆,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/ChinaMedia/ChinaMedia.list
ruleset=大陆,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Download/Download.list
ruleset=大陆,https://raw.githubusercontent.com/olddoge/ACL4SSR-Aznable/refs/heads/master/Ruleset/NoProxy.list
ruleset=群晖DDNS,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/NaSDDNS/NaSDDNS.list
; Emby 公益服
ruleset=Emby共享,https://raw.githubusercontent.com/olddoge/ACL4SSR-Aznable/refs/heads/master/Ruleset/EmbyShare.list
; AI 相关
ruleset=AI,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Claude/Claude.list
ruleset=AI,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/OpenAI/OpenAI.list
ruleset=AI,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Gemini/Gemini.list
; 微软服务
ruleset=Bing,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Bing/Bing.list
ruleset=OneDrive,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/OneDrive/OneDrive.list
ruleset=Microsoft,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Microsoft/Microsoft.list
; 苹果服务
ruleset=Apple智能,https://raw.githubusercontent.com/olddoge/ACL4SSR-Aznable/refs/heads/master/Ruleset/AppleIntelligence.list
ruleset=Apple专用代理,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/iCloudPrivateRelay/iCloudPrivateRelay.list
ruleset=Apple,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Apple/Apple_All.list
; Google
ruleset=Google,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Google/Google.list
ruleset=Google,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/GoogleFCM/GoogleFCM.list
ruleset=Google,[]DOMAIN-SUFFIX,xn--ngstr-lra8j.com
ruleset=Google,[]DOMAIN-SUFFIX,services.googleapis.cn
; Paypal
ruleset=PayPal,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/PayPal/PayPal.list
; Steam
ruleset=Steam,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Steam/Steam.list
ruleset=SteamCN,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/SteamCN/SteamCN.list
ruleset=SteamCN,https://raw.githubusercontent.com/olddoge/ACL4SSR-Aznable/refs/heads/master/Ruleset/SteamRegionCheck.list
; Sony
ruleset=Sony,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Sony/Sony.list
; 游戏下载
ruleset=游戏下载,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Game/GameDownloadCN/GameDownloadCN.list
ruleset=游戏下载,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Game/GameDownload/GameDownload.list
; 流媒体
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/HBO/HBO.list
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/YouTube/YouTube.list
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/YouTubeMusic/YouTubeMusic.list
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Twitch/Twitch.list
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/TikTok/TikTok.list
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Netflix/Netflix.list
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Disney/Disney.list
ruleset=流媒体,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Spotify/Spotify.list
; 社交网络
ruleset=社交网络,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Discord/Discord.list
ruleset=社交网络,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Facebook/Facebook.list
ruleset=社交网络,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Instagram/Instagram.list
ruleset=社交网络,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Reddit/Reddit.list
ruleset=社交网络,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Telegram/Telegram.list
ruleset=社交网络,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Threads/Threads.list
ruleset=社交网络,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Twitter/Twitter.list
; 开发者
ruleset=开发者,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/GitHub/GitHub.list
ruleset=开发者,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Docker/Docker.list
; 日本服务
ruleset=日本服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/DMM/DMM.list
ruleset=日本服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/DAZN/DAZN.list
ruleset=日本服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/HuluJP/HuluJP.list
ruleset=日本服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Niconico/Niconico.list
ruleset=日本服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Pixiv/Pixiv.list
; 美国服务
ruleset=美国服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/Fox/Fox.list
ruleset=美国服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/USMedia/USMedia.list
; 欧洲服务
ruleset=欧洲服务,https://cdn.jsdelivr.net/gh/blackmatrix7/ios_rule_script@master/rule/Surge/BBC/BBC.list
; 屏蔽日本
ruleset=屏蔽日本,https://raw.githubusercontent.com/olddoge/ACL4SSR-Aznable/refs/heads/master/Ruleset/NoJapan.list
; 剩余其他
ruleset=大陆,[]GEOIP,CN
ruleset=海外,[]FINAL

; 设置分组标志位开始
custom_proxy_group=大陆`select`[]DIRECT
custom_proxy_group=Emby共享`url-test`(emby)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=自动`url-test`.*`http://www.gstatic.com/generate_204`300,5,100
custom_proxy_group=香港节点`url-test`(香港|HK)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=美国节点`url-test`(美国|US)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=日本节点`url-test`(日本|JP)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=韩国节点`url-test`(韩国|KR)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=新加坡节点`url-test`(新加坡|SG)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=欧洲节点`url-test`(英国|UK|法国|FR|意大利|IT|德国)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=台湾节点`url-test`(台湾|TW)`http://www.gstatic.com/generate_204`180,5,100
custom_proxy_group=节点`select`[]日本节点`[]香港节点`[]台湾节点`[]韩国节点`[]新加坡节点`[]美国节点`[]欧洲节点`[]大陆`[]自动
custom_proxy_group=拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=海外`select`[]节点`[]香港节点`[]台湾节点`[]韩国节点`[]新加坡节点`[]美国节点`[]欧洲节点`[]自动
custom_proxy_group=检查`select`[]节点
; AI相关
custom_proxy_group=AI`select`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]节点`[]自动
; Google相关
custom_proxy_group=Google`select`[]节点`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
; Apple相关
custom_proxy_group=Apple智能`select`[]节点`[]日本节点`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动`[]大陆
custom_proxy_group=Apple专用代理`select`[]节点`[]日本节点`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动`[]大陆
custom_proxy_group=Apple`select`[]大陆`[]节点`[]日本节点`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
; 微软相关
custom_proxy_group=Microsoft`select`[]大陆`[]节点`[]日本节点`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
custom_proxy_group=Bing`select`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]节点`[]自动
custom_proxy_group=OneDrive`select`[]节点`[]日本节点`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动`[]大陆
; Paypal
custom_proxy_group=PayPal`select`[]节点`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动`[]大陆
; Steam相关
custom_proxy_group=Steam`select`[]节点`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
custom_proxy_group=SteamCN`select`[]大陆`[]节点`[]日本节点`[]美国节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
; 索尼相关
custom_proxy_group=Sony`select`[]节点`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动`[]大陆
; 游戏下载
custom_proxy_group=游戏下载`select`[]大陆`[]节点
; 流媒体
custom_proxy_group=流媒体`select`[]节点`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
; 社交网络
custom_proxy_group=社交网络`select`[]节点`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
; 开发者
custom_proxy_group=开发者`select`[]节点`[]美国节点`[]日本节点`[]新加坡节点`[]香港节点`[]台湾节点`[]韩国节点`[]欧洲节点`[]自动
; 群晖直连
custom_proxy_group=群晖DDNS`select`[]大陆`[]节点
; 日本节点专用
custom_proxy_group=日本节点服务`select`[]日本节点`[]节点
; 美国节点专用
custom_proxy_group=美国节点服务`select`[]美国节点`[]节点
; 欧洲节点专用专用
custom_proxy_group=欧洲节点服务`select`[]欧洲节点`[]节点
; 绕开日本节点
custom_proxy_group=屏蔽日本节点`select`[]台湾节点`[]香港节点`[]美国节点`[]新加坡节点`[]韩国节点`[]欧洲节点`[]大陆

;设置分组标志位结束

enable_rule_generator=true
overwrite_original_rules=true
